package com.example.reeltime.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.runtime.livedata.observeAsState
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import com.example.reeltime.model.Movie
import com.example.reeltime.ui.MovieViewModel

/**
 * The landing screen of the ReelTime app.
 * 
 * This screen displays personalized movie recommendations generated by the Gemini AI.
 * It observes the user's saved movie library and automatically updates recommendations
 * when the library content changes.
 *
 * @param viewModel The shared [MovieViewModel] providing movie data and AI logic.
 * @param onMovieClick Callback triggered when a movie is selected (for future implementation).
 */
@Composable
fun HomeScreen(
    viewModel: MovieViewModel,
    onMovieClick: (Movie) -> Unit
) {
    // Observe state from ViewModel. Using 'by' for property delegation to simplify access.
    val responseText by viewModel.aiRecommendations
    val isLoading by viewModel.isAiLoading
    val allMovies by viewModel.movies.observeAsState(emptyList())

    /**
     * Generate the AI prompt based on the current state of the user's library.
     * 
     * If the library is empty, it requests general popular movies.
     * If movies are present, it lists them with ratings to provide context for personalization.
     * The 'remember' block ensures the prompt is only recalculated when [allMovies] changes.
     */
    val prompt = remember(allMovies) {
        if (allMovies.isEmpty()) {
            "Recommend some of the highest rated and most popular movies of all time across various genres. Provide a diverse list with brief descriptions."
        } else {
            val movieDetails = allMovies.joinToString("\n") { movie ->
                "- ${movie.title} (${movie.releaseDate?.take(4) ?: "N/A"}), My Rating: ${movie.userRating ?: "Not rated"}, TMDB Average: ${movie.voteAverage}/10"
            }
            "I have already saved the following movies in my library:\n$movieDetails\n\n" +
            "IMPORTANT: Do not recommend any of the movies I have already saved. " +
            "Based on my interest in these specific movies, recommend 5 to 7 new movies I might enjoy. " +
            "For each recommendation, briefly explain why it matches my taste based on the movies I've saved."
        }
    }

    /**
     * Side effect that triggers the AI fetch whenever the [prompt] changes.
     * The ViewModel internally handles deduplication and job cancellation.
     */
    LaunchedEffect(prompt) {
        viewModel.fetchAiRecommendations(prompt)
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text(
            text = "Recommendations",
            style = MaterialTheme.typography.headlineMedium,
            fontWeight = FontWeight.Bold
        )

        // Display a loading state or the AI-generated content
        if (isLoading) {
            Box(
                modifier = Modifier.fillMaxSize(),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = "Analyzing your taste and finding the best movies...",
                    textAlign = TextAlign.Center,
                    style = MaterialTheme.typography.bodyLarge
                )
            }
        } else {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .verticalScroll(rememberScrollState()),
                contentAlignment = Alignment.TopCenter
            ) {
                Text(
                    text = responseText,
                    style = MaterialTheme.typography.bodyLarge,
                    textAlign = TextAlign.Start,
                    modifier = Modifier.padding(bottom = 16.dp)
                )
            }
        }
    }
}

